<?php
/**
 * SAGIPL
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   	SAGIPL
 * @package	Sag_Gallery
 * @copyright  	Copyright (c) 2014 SAGIPL. (http://www.sagipl.com/)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Simple Images Gallery with Categories
 *
 * @category	SAGIPL
 * @package	Sag_Gallery
 * @author	Navneet <navneet.kshk@gmail.com>
 */
?>
<div class="page-title">
    <h1><?php $this->getCategoryById(); ?></h1>
</div>

<?php
$collection = $this->getCollection();
$cnt = count($collection);
if($cnt > 0 ): 
?>
	<?php echo $this->getPagerHtml(); ?>
	<ul id="gallery_con">
		<?php foreach ($collection as $item): ?>                  
        <li>
            <a class="image_gal" href="<?php echo Mage::getUrl('gallery');?>image/?img=<?php   echo $item->getGalleryId(); ?>">
                <img src="<?php echo $this->resizeImage($item->getFilename(), 208, 230, ''); ?>" alt="<?php   echo $item->getTitle(); ?>" />
            </a>
            <a class="link_gal" href="<?php echo Mage::getUrl('gallery');?>image/?img=<?php   echo $item->getGalleryId(); ?>"><?php   echo $item->getTitle(); ?></a>
        </li>
        <?php endforeach;  ?> 
    </ul>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
	<div>There is no Images here</div>
<?php endif; ?>



<?php /*?><?php $cnt = count($this->getGallery()); ?>
<?php if($cnt > 0 ): ?>
	<ul id="gallery_con">
		<?php foreach ($this->getGallery() as $item): ?>                  
        <li>
            <a class="image_gal" href="../image/?img=<?php   echo $item->getGalleryId(); ?>">
                <img src="<?php echo $this->resizeImage($item->getFilename(), 208, 230, ''); ?>" alt="<?php   echo $item->getTitle(); ?>" />
            </a>
            <a class="link_gal" href="../image/?img=<?php   echo $item->getGalleryId(); ?>"><?php   echo $item->getTitle(); ?></a>
        </li>
        <?php endforeach;  ?> 
    </ul>
<?php else: ?>
	<div>There is no Images here</div>
<?php endif; ?>
<?php echo $this->getPagerHtml(); ?><?php */?>